export const BROWSE = {
  HEADER_SUB_TEXT: "Discover potential cofounders.",
  NAME_SEARCH_PLACEHOLDER: "Search by name",
  SKILL_SEARCH_PLACEHOLDER: "Enter skills to filter by",
  USER_TIER_LOADING_ERROR: "An error occured loading user tier. Please try again later.",
  SEARCH_INSTRUCTION_MESSAGE: "Choose your filters and click Search to get started.",
  SEARCH_ERROR: "Whoops! An error occured.",
  NEXT_PAGE_LOAD_ERROR: "Something went wrong while loading more results.",
  PAGINATION_END: "Looks like you’ve seen everything.",
  SEARCH_RESULTS_EMPTY: "No results found. Try adjusting your search.",
  LOOKING_FOR_SKILL_SEARCH_PLACEHOLDER: "Filter by skills others are seeking",
  PARAM_LOCATION: "location",
  PARAM_VALUE_ANY_COUNTRY: "anywhere",
  PARAM_SKILLS: "skills",
  PARAM_ROLES: "roles",
  PARAM_COMMITMENT_LEVELS: "commitmentLevels",
  PARAM_AVAILABILITY: "availabilities",
  PARAM_PROFILE_TYPE: "profileType",
  PARAM_PREFERRED_STARTUP_STAGES: "preferredStartupStages",
  PARAM_VALUE_STARTUP_OWNER: "startupOwner",
  PARAM_VALUE_STARTUP_SEEKER: "startupSeeker",
  PARAM_SKILLS_SOUGHT: "skillsSought",
  PARAM_ROLES_SOUGHT: "rolesSought",
  PARAM_COMMITMENT_LEVELS_SOUGHT: "commitmentLevelsSought",
  PARAM_AVAILABILITY_SOUGHT: "availabilitiesSought",
  MAX_RETRIES: 5,
};
