export const BROWSE = {
  HEADER_SUB_TEXT: "Discover potential cofounders.",
  SKILL_SEARCH_PLACEHOLDER: "Enter skills to filter by",
  LOOKING_FOR_SKILL_SEARCH_PLACEHOLDER: "Filter by skills others are seeking",
  PARAM_LOCATION: "location",
  PARAM_SKILLS: "skills",
  PARAM_ROLES: "roles",
  PARAM_COMMITMENT_LEVELS: "commitmentLevels",
  PARAM_AVAILABILITY: "availability",
  PARAM_PROFILE_TYPE: "profileType",
  PARAM_PREFERRED_STARTUP_STAGES: "preferredStartupStages",
  PARAM_VALUE_STARTUP_OWNER: "startupOwner",
  PARAM_VALUE_STARTUP_SEEKER: "startupSeeker",
  PARAM_SKILLS_SOUGHT: "skillsSought",
  PARAM_ROLES_SOUGHT: "rolesSought",
  PARAM_COMMITMENT_LEVELS_SOUGHT: "commitmentLevelsSought",
  PARAM_AVAILABILITY_SOUGHT: "availabilitySought",
};
