export const SETTINGS = {
  SUBTITLE_TEXT: "Manage your account preferences and profile settings.",
  RESET_BUTTON_TEXT: "Discard changes",
  UPDATE_BUTTON_TEXT: "Update",
  ADD_SKILL_BUTTON_TEXT: "Add skill",
  NO_SKILLS_PARAGRAPH_TEXT: "You have not added any skills.",
  NO_ROLES_PARAGRAPH_TEXT: "You have not selected any roles.",
  MAX_HEADLINE_LENGTH: 100,
  MAX_BIO_LENGTH: 1500,
  MAX_STARTUP_DESCRIPTION_LENGTH: 1500,
  MAX_SKILL_COUNT: 10,
  MAX_ROLE_COUNT: 5,
  MINIMUM_RENDER_CHARACTER_COUNT: 4,
  MAX_COMPANY_STAGES_LENGTH: 5,
  COMPLETE_BASIC_PROFILE: "Complete your basic profile information.",
  COMPLETE_PROFESSIONAL_INFORMATION: "Complete your professional information.",
  COMPLETE_STARTUP_INFORMATION: "Complete your startup information.",
  COMPLETE_MATCHING_PREFERENCES: "Complete your matching preferences.",
  COMPLETE_SOCIAL_PROFILES: "Complete your social profiles.",
  DICEBEAR_API_URL: "https://api.dicebear.com/9.x/initials/svg?seed=",
  ACCEPTED_IMAGE_TYPES: ["image/png", "image/jpeg", "image/jpg", "image/webp"],
  MAX_IMAGE_SIZE_BYTES: 1 * 1024 * 1024,
  BASIC_MAX_CONTACTS: 5,
  BASIC_MAX_CHATS: 5,
};
