// All authentication-related constants

export const SIGNUP = {
  GREETING_TEXT: "Hi, let's get you started.",
  SIGNUP_BUTTON_TEXT: "Continue",
  SIGNUP_WITH_GOOGLE_BUTTON_TEXT: "Continue with Google",
  MAXIMUM_FIRST_NAME_LENGTH: 50,
  MAXIMUM_LAST_NAME_LENGTH: 50,
  MAXIMUM_EMAIL_LENGTH: 254,
  MINIMUM_AGE: 16,
  MAXIMUM_AGE: 100,
  MAXIMUM_PASSWORD_LENGTH: 128,
  MINIMUM_FIRST_NAME_LENGTH: 1,
  MINIMUM_LAST_NAME_LENGTH: 1,
  MINIMUM_PASSWORD_LENGTH: 8,
  FIRST_NAME_LENGTH_ERROR: "Please enter your first name.",
  LAST_NAME_LENGTH_ERROR: "Please enter your last name.",
  EMAIL_INVALID_ERROR: "Please enter a valid email address.",
  DATE_OF_BIRTH_ERROR: "Please enter a valid age.",
  PASSWORD_LENGTH_ERROR: "Password must at least be 8 characters.",
  PASSWORDS_DO_NOT_MATCH_ERROR: "The passwords do not match.",
  EMAIL_ALREADY_IN_USE: "This email address is already associated with an account.",
  TOO_MANY_ATTEMPTS: "Too many attempts. Please try again later.",
  NETWORK_ERROR: "A network error occured. Please check your internet connection and try again.",
  ACCOUNT_EXISTS_WITH_DIFFERENT_SIGNIN_METHOD:
    "An account already exists with this email using a different sign-in method.",
  POPUP_BLOCKED: "Your browser blocked the sign-in popup. Please allow popups and try again.",
  POPUP_CLOSED: "Sign-in popup was closed before completing the sign-in.",
  UNAUTHORIZED_DOMAIN: "This app is not authorized for Google sign-in. Contact support.",
  UNAUTHENTICATED: "The user is unauthenticated",
  UNKNOWN_ERROR: "An unexpected error occured. Please try again later.",
  SIGNOUT_SUCCESS: "You have been signed out of your account.",
};
